Repository newrelic/go-agent, pull requests merged in 2021-05, with the labels that each got.

#304 updated version.go and release notes for 3.12.0
  CHANGELOG.md
  v3/newrelic/version.go
Labels: documentation

#314 Getting http2 and grpc to run on old Go
  build-script.sh
Labels: ready-for-review

#317 fix issue 221: grpc error reporting
  v3/integrations/nrgrpc/go.mod
  v3/integrations/nrgrpc/nrgrpc_server.go
  v3/integrations/nrgrpc/nrgrpc_server_test.go
Labels: bug
