Repository newrelic/go-agent, pull requests merged in 2021-03, with the labels that each got.

#276 Change logging level for 8T rebalancing messages
  CHANGELOG.md
  ROADMAP.md
  v3/newrelic/trace_observer.go
Labels: ready-for-review

#278 Log panic stack traces
  v3/newrelic/internal_txn.go
Labels: bug

#251 Added support for `v8` of go-redis/redis
  v3/integrations/nrredis-v8/README.md
  v3/integrations/nrredis-v8/example/main.go
  v3/integrations/nrredis-v8/go.mod
  v3/integrations/nrredis-v8/nrredis.go
  v3/integrations/nrredis-v8/nrredis_example_test.go
  v3/integrations/nrredis-v8/nrredis_test.go
Labels: p2, size

#233 Adds Aerospike in Datastore
  datastore.go
  v3/newrelic/datastore.go
Labels: enhancement, p2

#279 Added support for `v8` of [go-redis/redis](https://github.com/go-redi…
  v3/integrations/nrredis-v8/README.md
  v3/integrations/nrredis-v8/example/main.go
  v3/integrations/nrredis-v8/go.mod
  v3/integrations/nrredis-v8/nrredis.go
  v3/integrations/nrredis-v8/nrredis_example_test.go
  v3/integrations/nrredis-v8/nrredis_test.go
Labels: p1

#280 Update some OSS links per repo-linter
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: p1
